.bowerrc, .gitignore, app/Http/Livewire/HomeComponent.php, bower.json, composer.lock, resources/views/layouts/base.blade.php, resources/views/livewire/home-component.blade.php, routes/web.php
- [#40577](https://edu-redmine.sun-asterisk.vn/issues/40577)
Create base layout
- N/A.
- N/A.
=> create base layout

app/Http/Livewire/CartComponent.php, app/Http/Livewire/CheckoutComponent.php, app/Http/Livewire/ShopComponent.php, resources/views/layouts/base.blade.php, resources/views/livewire/cart-component.blade.php, resources/views/livewire/checkout-component.blade.php, resources/views/livewire/home-component.blade.php, resources/views/livewire/shop-component.blade.php, routes/web.php
- [#40578](https://edu-redmine.sun-asterisk.vn/issues/40578)
Create shop, cart and checkout page
- N/A.
- N/A.
=> add Cart, Checkout, Shop layout

PULL_REQUEST_TEMPLATE.md, app/Http/Kernel.php, app/Http/Livewire/Admin/AdminDashboardComponent.php, app/Http/Livewire/User/UserDashboardComponent.php, app/Http/Middleware/AuthAdmin.php, app/Providers/RouteServiceProvider.php, database/migrations/2014_10_12_000000_create_users_table.php, public/mix-manifest.json, resources/js/index.js, resources/views/layouts/base.blade.php, resources/views/livewire/admin/admin-dashboard-component.blade.php, resources/views/livewire/user/user-dashboard-component.blade.php, routes/web.php, webpack.mix.js
- [#40580](https://edu-redmine.sun-asterisk.vn/issues/40580)
Admin and user authentication
Add layout for admin and user dashboard
- N/A.
- N/A.
=> Admin and user authentication

app/Http/Livewire/CartComponent.php, app/Http/Livewire/DetailsComponent.php, app/Http/Livewire/ShopComponent.php, composer.json, composer.lock, config/app.php, config/constant.php, resources/lang/en/cart.php, resources/lang/en/shop.php, resources/lang/vi/cart.php, resources/lang/vi/shop.php, resources/views/layouts/base.blade.php, resources/views/layouts/guest.blade.php, resources/views/livewire/cart-component.blade.php, resources/views/livewire/details-component.blade.php, resources/views/livewire/search-component.blade.php, resources/views/livewire/shop-component.blade.php
- [#40585](https://edu-redmine.sun-asterisk.vn/issues/40585)
Create shopping cart
- N/A.
- N/A.
=> shopping cart

app/Http/Livewire/Admin/AdminAddProductComponent.php, app/Http/Livewire/Admin/AdminEditProductComponent.php, app/Http/Livewire/Admin/AdminProductComponent.php, app/Models/Images.php, app/Models/Product.php, config/constant.php, config/filesystems.php, resources/lang/en/admin-product.php, resources/lang/en/shop.php, resources/lang/vi/admin-product.php, resources/lang/vi/shop.php, resources/views/layouts/base.blade.php, resources/views/livewire/admin/admin-add-product-component.blade.php, resources/views/livewire/admin/admin-edit-product-component.blade.php, resources/views/livewire/admin/admin-product-component.blade.php, resources/views/livewire/search-component.blade.php, routes/web.php
- [#40596](https://edu-redmine.sun-asterisk.vn/issues/40596)
admin CRUD product
- N/A.
- N/A.
=> Admin CRUD product

app/Http/Livewire/CategoryComponent.php, app/Http/Livewire/DetailsComponent.php, app/Http/Livewire/ShopComponent.php, config/constant.php, resources/lang/en/shop.php, resources/lang/vi/shop.php, resources/views/livewire/category-component.blade.php, routes/web.php
- [#40589](https://edu-redmine.sun-asterisk.vn/issues/40589)
Products by category
- N/A.
- N/A.
=> products by category

app/Http/Livewire/CartComponent.php, app/Models/Order.php, app/Models/Shipping.php, app/Models/Transaction.php, database/migrations/2021_08_31_010740_create_orders_table.php, database/migrations/2021_08_31_010834_create_shippings_table.php, database/migrations/2021_08_31_010929_create_transactions_table.php, database/migrations/2021_08_31_035058_create_order_product_table.php, resources/lang/en/cart.php, resources/lang/vi/cart.php, resources/views/livewire/cart-component.blade.php
- [#40604](https://edu-redmine.sun-asterisk.vn/issues/40604)
Setting for checkout
- N/A.
- N/A.
=> setting for checkout

app/Http/Livewire/CartComponent.php, app/Http/Livewire/CartCountComponent.php, resources/views/layouts/base.blade.php, resources/views/livewire/cart-count-component.blade.php
- [#41082](https://edu-redmine.sun-asterisk.vn/issues/41082)
update cart count
- N/A.
- N/A.
=> update cart count

app/Http/Livewire/Admin/AdminAddCategoryComponent.php, app/Http/Livewire/Admin/AdminCategoryComponent.php, app/Http/Livewire/Admin/AdminEditCategoryComponent.php, app/Models/Category.php, config/constant.php, resources/lang/en/categories.php, resources/lang/vi/categories.php, resources/views/layouts/base.blade.php, resources/views/livewire/admin/admin-add-category-component.blade.php, resources/views/livewire/admin/admin-category-component.blade.php, resources/views/livewire/admin/admin-edit-category-component.blade.php, routes/web.php
- [#40592](https://edu-redmine.sun-asterisk.vn/issues/40592)
Admin crud category
- N/A.
- N/A.
=> admin crud category

app/Http/Livewire/CartComponent.php, app/Http/Livewire/CheckoutComponent.php, app/Http/Livewire/SearchComponent.php, app/Http/Livewire/ThankyouComponent.php, app/Models/Order.php, config/constant.php, resources/lang/en/checkout.php, resources/lang/en/thankyou.php, resources/lang/vi/checkout.php, resources/lang/vi/thankyou.php, resources/views/livewire/checkout-component.blade.php, resources/views/livewire/thankyou-component.blade.php, routes/web.php
- [#40607](https://edu-redmine.sun-asterisk.vn/issues/40607)
checkout COD
- N/A.
- N/A.
=> Checkout COD

app/Http/Livewire/User/UserProfileComponent.php, resources/lang/en/home.php, resources/lang/en/user-profile.php, resources/lang/vi/home.php, resources/lang/vi/user-profile.php, resources/views/layouts/base.blade.php, resources/views/livewire/user/user-profile-component.blade.php, routes/web.php
- [#40624](https://edu-redmine.sun-asterisk.vn/issues/40624)
edit profile user
- N/A.
- N/A.
=> edit profile user

app/Http/Livewire/User/UserOderDetailsComponent.php, app/Http/Livewire/User/UserOrdersComponent.php, public/mix-manifest.json, resources/css/orders.css, resources/lang/en/orders.php, resources/lang/vi/orders.php, resources/views/layouts/base.blade.php, resources/views/livewire/user/user-oder-details-component.blade.php, resources/views/livewire/user/user-orders-component.blade.php, routes/web.php, webpack.mix.js
- [#40611](https://edu-redmine.sun-asterisk.vn/issues/40611)
User manages orders
- N/A.
- N/A.
=> User manages orders

app/Http/Livewire/Admin/AdminAddProductComponent.php, resources/lang/en/admin-product.php, resources/lang/vi/admin-product.php, resources/views/livewire/admin/admin-add-product-component.blade.php
- [#40620](https://edu-redmine.sun-asterisk.vn/issues/40620)
add product gallery
- N/A.
- N/A.
=> add product gallery

app/Http/Livewire/Admin/AdminDashboardComponent.php, app/Http/Livewire/CheckoutComponent.php, app/Models/Order.php, resources/lang/en/admin-dashboard.php, resources/lang/vi/admin-dashboard.php, resources/views/livewire/admin/admin-dashboard-component.blade.php
- [#40618](https://edu-redmine.sun-asterisk.vn/issues/40618)
add layout admin dashboard
- N/A.
- N/A.
=> add layout admin dashboard

app/Http/Livewire/Admin/AdminManageUserComponent.php, app/Http/Middleware/AuthAdmin.php, app/Providers/JetstreamServiceProvider.php, config/constant.php, public/mix-manifest.json, resources/css/toggle-button.css, resources/lang/en/auth.php, resources/lang/en/home.php, resources/lang/en/users_management.php, resources/lang/vi/auth.php, resources/lang/vi/home.php, resources/lang/vi/users_management.php, resources/views/auth/login.blade.php, resources/views/layouts/base.blade.php, resources/views/layouts/guest.blade.php, resources/views/livewire/admin/admin-manage-user-component.blade.php, routes/web.php, webpack.mix.js
- [#40627](https://edu-redmine.sun-asterisk.vn/issues/40627)
Admin manges account of users
- N/A.
- N/A.
=> user management

app/Http/Livewire/Admin/AdminProductComponent.php
- [#41172](https://edu-redmine.sun-asterisk.vn/issues/41172)
fix product deletion bug when the product has been in cart.
- N/A.
- N/A.
=> fix product deletion bug

app/Http/Livewire/Admin/AdminProductComponent.php, resources/views/livewire/cart-component.blade.php, resources/views/livewire/category-component.blade.php, routes/web.php
- [#41173](https://edu-redmine.sun-asterisk.vn/issues/41173)
fix bug  products by category
- N/A.
- N/A.
=> fix bug  products by category

app/Http/Livewire/DetailsComponent.php, app/Http/Livewire/User/UserReviewComponent.php, app/Models/Product.php, app/Models/Review.php, database/migrations/2021_09_01_013628_create_reviews_table.php, resources/lang/en/review.php, resources/lang/vi/review.php, resources/views/livewire/details-component.blade.php, resources/views/livewire/user/user-oder-details-component.blade.php, resources/views/livewire/user/user-review-component.blade.php, routes/web.php
- [#40614](https://edu-redmine.sun-asterisk.vn/issues/40614)
add review and rating
- N/A.
- N/A.
=> add review and rating

app/Http/Livewire/Admin/AdminEditProductComponent.php, app/Http/Livewire/ShopComponent.php, resources/views/livewire/admin/admin-category-component.blade.php, resources/views/livewire/admin/admin-edit-product-component.blade.php, resources/views/livewire/cart-component.blade.php, resources/views/livewire/category-component.blade.php, resources/views/livewire/search-component.blade.php, resources/views/livewire/shop-component.blade.php
- [#41230](https://edu-redmine.sun-asterisk.vn/issues/41230)
fix edit product bug
- N/A.
- N/A.
=> fix edit product bug

database/factories/HomeCategoryFactory.php, database/seeders/DatabaseSeeder.php
- [#41240](https://edu-redmine.sun-asterisk.vn/issues/41240)
add seed for homecategory and admin
- N/A.
- N/A.
=> add seed for homecategory and admin

app/Http/Livewire/CategoryComponent.php, resources/views/livewire/category-component.blade.php
- [#41319](https://edu-redmine.sun-asterisk.vn/issues/41319)
fix add to cart bug
- N/A.
- N/A.
=> fix add to cart bug
